# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # if you don't do these things before calling goreleaser, it might be a
    # good idea to do them here:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    id: cogrs
    binary: cogrs
    flags:
      - --release
      - -p=cogrs
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
  - builder: rust
    id: command
    binary: command
    flags:
      - --release
      - -p=command
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
  - builder: rust
    id: minimal-linux
    binary: libminimal.so
    flags:
      - --release
      - -p=minimal
    env:
      - CGO_ENABLED=1
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
  - builder: rust
    id: minimal-apple
    binary: libminimal.dylib
    flags:
      - --release
      - -p=minimal
    env:
      - CGO_ENABLED=1
    targets:
      - x86_64-apple-darwin
      - aarch64-apple-darwin
  - builder: rust
    id: ssh-apple
    binary: libssh.dylib
    flags:
      - --release
      - -p=ssh
    env:
      - CGO_ENABLED=1
    targets:
      - x86_64-apple-darwin
      - aarch64-apple-darwin
  - builder: rust
    id: sh-apple
    binary: libsh.dylib
    flags:
      - --release
      - -p=sh
    env:
      - CGO_ENABLED=1
    targets:
      - x86_64-apple-darwin
      - aarch64-apple-darwin
archives:
  - format: tar.gz
    id: cogrs
    name_template: >-
      {{ .ProjectName }}_cli_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    builds:
      - cogrs
    format_overrides:
      - goos: windows
        format: zip

  - format: tar.gz
    id: command
    name_template: >-
      {{ .ProjectName }}_command_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    builds:
      - command
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
