[package]
name = "cogrs-plugins"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.138"
once_cell = "1.20.3"
libloading = "0.8.6"
anyhow = "1.0.95"
tokio = { version = "1.43.0", features = ["full"] }
