[package]
name = "cogrs-modules"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.138"
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
cogrs-schema = { path = "../cogrs-schema" }
