COGRS_HOME:
  name: The CogRS home path
  description:
    - The default root path for CogRS config files on the controller.
  default: ~/.cogrs
  env:
    - name: COGRS_HOME
  ini:
    - key: home
      section: defaults
  type: path
DEFAULT_CALLBACK_PLUGIN_PATH:
  name: Callback Plugins Path
  default: '{{ COGRS_HOME ~ "/plugins/callback:/usr/share/cogrs/plugins/callback" }}'
  description: Colon-separated paths in which CogRS will search for Callback Plugins.
  env: [{name: COGRS_CALLBACK_PLUGINS}]
  ini:
    - {key: callback_plugins, section: defaults}
  type: path
  yaml: {key: plugins.callback.path}
DEFAULT_SHELL_PLUGIN_PATH:
  name: Shell Plugins Path
  default: '{{ COGRS_HOME ~ "/plugins/shell:/usr/share/cogrs/plugins/shell" }}'
  description: Colon-separated paths in which CogRS will search for Shell Plugins.
  env: [{name: COGRS_SHELL_PLUGINS}]
  ini:
    - {key: shell_plugins, section: defaults}
  type: path
  yaml: {key: plugins.shell.path}
DEFAULT_CONNECTION_PLUGIN_PATH:
  name: Connection Plugins Path
  default: '{{ COGRS_HOME ~ "/plugins/connection:/usr/share/cogrs/plugins/connection" }}'
  description: Colon-separated paths in which CogRS will search for Connection Plugins.
  env: [{name: COGRS_CONNECTION_PLUGINS}]
  ini:
    - {key: connection_plugins, section: defaults}
  type: path
  yaml: {key: plugins.connection.path}
DEFAULT_LOCAL_TMP:
  name: Controller temporary directory
  default: '{{ COGRS_HOME ~ "/tmp" }}'
  description: Temporary directory for CogRS to use on the controller.
  env: [{name: COGRS_LOCAL_TEMP}]
  ini:
    - {key: local_tmp, section: defaults}
  type: path
