name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run coverage and generate LCOV
      run: cargo tarpaulin --out Lcov

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2.3.6
      with:
        path-to-lcov: ./tarpaulin.lcov

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
